apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chessbookweb
spec:
  template:
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/afonso-benedito/chessbookweb/chessbookweb:latest
          env:
            - name: DB_PATH
              value: /tmp/chess.db
            - name: SESSION_SECRET
              value: REPLACE_WITH_SECRET
          resources:
            limits:
              memory: 256Mi
              cpu: 1000m
      containerConcurrency: 80
      timeoutSeconds: 3600
